import { Injectable, Logger } from '@nestjs/common';
import { promises as fs } from 'node:fs';
import path from 'node:path';

import type { DesignTokens, ProjectSpec } from '../ai/ai.types';
import { AiService } from '../ai/ai.service';

const RESET_OUTPUT_ATTEMPTS = 6;
const RESET_OUTPUT_RETRY_DELAY_MS = 1000;

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface ProjectManifest {
  projectType: string;
  title: string;
  entrypoint: string;
  files: string[];
  commands: {
    install: string;
    dev: string;
    build: string;
  };
}

@Injectable()
export class CodeGeneratorService {
  private readonly logger = new Logger(CodeGeneratorService.name);

  constructor(private readonly aiService: AiService) {}

  /**
   * Generate all project files — scaffolding is templated, UI code comes from AI
   */
  async generateProjectFiles(
    brief: string,
    projectSpec: ProjectSpec,
    designTokens: DesignTokens,
    designDescription: string,
    codePath: string,
  ): Promise<GeneratedFile[]> {
    this.logger.log('Generating project files (scaffolding + AI code)');

    let generatedUiFiles: GeneratedFile[];
    try {
      const aiCode = await this.aiService.generateCode(
        brief,
        projectSpec,
        designTokens,
        designDescription,
      );
      generatedUiFiles = this.normalizeGeneratedFiles(aiCode.files);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      this.logger.warn(
        `AI code generation failed, using deterministic fallback: ${message}`,
      );
      generatedUiFiles = this.createFallbackUiFiles(projectSpec, designTokens);
    }

    const files: GeneratedFile[] = [
      {
        path: 'package.json',
        content: this.createPackageJson(projectSpec),
      },
      {
        path: 'next.config.mjs',
        content: this.createNextConfig(),
      },
      {
        path: 'tsconfig.json',
        content: this.createTsConfig(),
      },
      {
        path: 'tailwind.config.ts',
        content: this.createTailwindConfig(),
      },
      {
        path: 'postcss.config.mjs',
        content: this.createPostCssConfig(),
      },
      {
        path: 'next-env.d.ts',
        content:
          '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// This file is generated by Next.js.\n',
      },
      ...generatedUiFiles,
      {
        path: 'README.md',
        content: this.createReadme(projectSpec),
      },
    ];

    await this.resetOutputDirectory(codePath);
    await this.writeFiles(files, codePath);

    return files;
  }

  /**
   * Generate project manifest
   */
  generateManifest(
    projectSpec: ProjectSpec,
    files: GeneratedFile[],
  ): ProjectManifest {
    return {
      projectType: 'next-tailwind',
      title: projectSpec.copy.headline,
      entrypoint: 'src/app/page.tsx',
      files: files.map((file) => file.path),
      commands: {
        install: 'npm install --include=dev',
        dev: 'npm run dev',
        build: 'npm run build',
      },
    };
  }

  /**
   * Generate reference SVG via AI
   */
  async generateReferenceSvg(
    brief: string,
    projectSpec: ProjectSpec,
    designTokens: DesignTokens,
    designDescription: string,
  ): Promise<string> {
    return this.aiService.generateReferenceSvg(
      brief,
      projectSpec,
      designTokens,
      designDescription,
    );
  }

  private async writeFiles(
    files: GeneratedFile[],
    basePath: string,
  ): Promise<void> {
    await Promise.all(
      files.map(async (file) => {
        const filePath = path.join(basePath, file.path);
        const dir = path.dirname(filePath);
        await fs.mkdir(dir, { recursive: true });
        await fs.writeFile(filePath, file.content, 'utf8');
      }),
    );
  }

  private async resetOutputDirectory(basePath: string): Promise<void> {
    for (let attempt = 1; attempt <= RESET_OUTPUT_ATTEMPTS; attempt += 1) {
      try {
        await fs.rm(basePath, { recursive: true, force: true });
        await fs.mkdir(basePath, { recursive: true });
        return;
      } catch (error) {
        const code =
          error && typeof error === 'object' && 'code' in error
            ? String(error.code)
            : '';

        if (
          attempt >= RESET_OUTPUT_ATTEMPTS ||
          !['EBUSY', 'ENOTEMPTY', 'EPERM'].includes(code)
        ) {
          throw error;
        }

        this.logger.warn(
          `Code output directory is busy, retrying reset ${attempt}/${RESET_OUTPUT_ATTEMPTS}: ${basePath}`,
        );
        await new Promise((resolve) =>
          setTimeout(resolve, RESET_OUTPUT_RETRY_DELAY_MS * attempt),
        );
      }
    }
  }

  private createPackageJson(projectSpec: ProjectSpec): string {
    const packageName = projectSpec.copy.headline
      .toLowerCase()
      .replace(/[^a-zа-я0-9]+/gi, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 48);

    return `${JSON.stringify(
      {
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
        },
        dependencies: {
          next: '^15.1.0',
          react: '^19.0.0',
          'react-dom': '^19.0.0',
          clsx: '^2.1.1',
          'tailwind-merge': '^2.6.0',
          '@types/react': '^19.0.0',
          '@types/react-dom': '^19.0.0',
          autoprefixer: '^10.4.20',
          postcss: '^8.4.49',
          tailwindcss: '^3.4.17',
          typescript: '^5.7.0',
        },
        devDependencies: {},
        private: true,
        name: packageName || 'generated-landing',
        version: '0.0.0',
        type: 'module',
      },
      null,
      2,
    )}\n`;
  }

  private createNextConfig(): string {
    return `/** @type {import('next').NextConfig} */
import path from 'node:path';

const nextConfig = {
  reactStrictMode: true,
  outputFileTracingRoot: path.resolve(process.cwd()),
};

export default nextConfig;
`;
  }

  private createTsConfig(): string {
    return `${JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2017',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: false,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          baseUrl: '.',
          paths: {
            '@/*': ['./src/*'],
          },
          plugins: [{ name: 'next' }],
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules'],
      },
      null,
      2,
    )}\n`;
  }

  private createTailwindConfig(): string {
    return `import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/app/**/*.{ts,tsx}',
    './src/components/**/*.{ts,tsx}',
    './src/config/**/*.{ts,tsx}',
    './src/content/**/*.{ts,tsx}',
    './src/lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'var(--border)',
        input: 'var(--input, var(--border))',
        ring: 'var(--ring, var(--accent))',
        background: 'var(--background)',
        foreground: 'var(--foreground, var(--text-primary))',
        primary: {
          DEFAULT: 'var(--primary, var(--accent))',
          foreground: 'var(--primary-foreground, #ffffff)',
        },
        secondary: {
          DEFAULT: 'var(--secondary, var(--surface))',
          foreground: 'var(--secondary-foreground, var(--text-primary))',
        },
        muted: {
          DEFAULT: 'var(--muted, var(--surface))',
          foreground: 'var(--muted-foreground, var(--text-muted))',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground, #ffffff)',
        },
        card: {
          DEFAULT: 'var(--card, var(--surface-elevated))',
          foreground: 'var(--card-foreground, var(--text-primary))',
        },
        popover: {
          DEFAULT: 'var(--popover, var(--surface-elevated))',
          foreground: 'var(--popover-foreground, var(--text-primary))',
        },
        destructive: {
          DEFAULT: 'var(--destructive, #ef4444)',
          foreground: 'var(--destructive-foreground, #ffffff)',
        },
      },
    },
  },
  plugins: [],
};

export default config;
`;
  }

  private createPostCssConfig(): string {
    return `const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

export default config;
`;
  }

  private createReadme(projectSpec: ProjectSpec): string {
    return `# ${projectSpec.copy.headline}

Generated Next.js + Tailwind site.

## Commands

\`\`\`bash
npm install --include=dev
npm run dev
npm run build
\`\`\`
`;
  }

  private createFallbackUiFiles(
    projectSpec: ProjectSpec,
    designTokens: DesignTokens,
  ): GeneratedFile[] {
    const content = {
      productName: projectSpec.productName,
      productDescription: projectSpec.productDescription,
      navigation: projectSpec.navigation ?? {
        logo: projectSpec.productName,
        menuItems: projectSpec.sections.map((section) => section.title),
        ctaButton: projectSpec.copy.primaryButton,
      },
      hero: projectSpec.copy,
      metrics:
        projectSpec.metrics && projectSpec.metrics.length > 0
          ? projectSpec.metrics
          : [
              { value: '7', label: 'sections' },
              { value: '100%', label: 'responsive' },
              { value: '24/7', label: 'ready to launch' },
            ],
      sections: projectSpec.sections,
      cta: {
        title: projectSpec.copy.headline,
        description: projectSpec.copy.description,
        button: projectSpec.copy.primaryButton,
      },
    };
    const siteTitle = projectSpec.copy.headline;
    const siteDescription = projectSpec.copy.description;
    const cssVariables = this.createFallbackCssVariables(designTokens);

    return [
      {
        path: 'src/app/page.tsx',
        content: `import { LandingPage } from '@/components/landing/landing-page';\n\nexport default function Page() {\n  return <LandingPage />;\n}\n`,
      },
      {
        path: 'src/app/layout.tsx',
        content: `import type { Metadata } from 'next';\nimport './globals.css';\nimport { seoConfig } from '@/config/seo';\n\nexport const metadata: Metadata = seoConfig;\n\nexport default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {\n  return (\n    <html lang=\"ru\">\n      <body>{children}</body>\n    </html>\n  );\n}\n`,
      },
      {
        path: 'src/app/globals.css',
        content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n:root {\n${cssVariables}\n}\n\n* {\n  box-sizing: border-box;\n}\n\nhtml {\n  scroll-behavior: smooth;\n}\n\nbody {\n  margin: 0;\n  background: var(--color-background);\n  color: var(--color-text-primary);\n  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif;\n}\n\n::selection {\n  background: var(--color-accent);\n  color: white;\n}\n`,
      },
      {
        path: 'src/content/site-content.ts',
        content: `type Navigation = {\n  logo: string;\n  menuItems: string[];\n  ctaButton?: string | null;\n  authButton?: string | null;\n};\n\ntype Hero = {\n  badge?: string | null;\n  headline: string;\n  headlineAccent?: string | null;\n  description: string;\n  primaryButton: string;\n  secondaryButton: string;\n  trustLine?: string | null;\n};\n\ntype Metric = {\n  value: string;\n  label: string;\n};\n\ntype LandingSection = {\n  id: string;\n  type: string;\n  title: string;\n  goal: string;\n  contentNotes: string[];\n  visualNotes: string[];\n  requiredElements: string[];\n};\n\ntype SiteContent = {\n  productName: string;\n  productDescription: string;\n  navigation: Navigation;\n  hero: Hero;\n  metrics: Metric[];\n  sections: LandingSection[];\n  cta: {\n    title: string;\n    description: string;\n    button: string;\n  };\n};\n\nexport const siteContent: SiteContent = ${JSON.stringify(content, null, 2)};\n`,
      },
      {
        path: 'src/config/site.ts',
        content: `export const siteConfig = {\n  name: ${JSON.stringify(projectSpec.productName)},\n  title: ${JSON.stringify(siteTitle)},\n  description: ${JSON.stringify(siteDescription)},\n  url: 'https://example.com',\n  keywords: [${projectSpec.stylePreference.map((item) => JSON.stringify(item)).join(', ')}],\n} as const;\n`,
      },
      {
        path: 'src/config/seo.ts',
        content: `import type { Metadata } from 'next';\nimport { siteConfig } from './site';\n\nexport const seoConfig: Metadata = {\n  title: siteConfig.title,\n  description: siteConfig.description,\n  keywords: [...siteConfig.keywords],\n  openGraph: {\n    title: siteConfig.title,\n    description: siteConfig.description,\n    type: 'website',\n  },\n  robots: {\n    index: true,\n    follow: true,\n  },\n};\n`,
      },
      {
        path: 'src/lib/class-names.ts',
        content: `export function cn(...classes: Array<string | false | null | undefined>) {\n  return classes.filter(Boolean).join(' ');\n}\n`,
      },
      {
        path: 'src/components/ui/container.tsx',
        content: `import type { ReactNode } from 'react';\nimport { cn } from '@/lib/class-names';\n\nexport function Container({ children, className = '' }: { children: ReactNode; className?: string }) {\n  return <div className={cn('mx-auto w-full max-w-7xl px-5 sm:px-8 lg:px-10', className)}>{children}</div>;\n}\n`,
      },
      {
        path: 'src/components/seo/structured-data.tsx',
        content: `import { siteConfig } from '@/config/site';\n\nexport function StructuredData() {\n  const data = {\n    '@context': 'https://schema.org',\n    '@type': 'Organization',\n    name: siteConfig.name,\n    description: siteConfig.description,\n  };\n\n  return <script type=\"application/ld+json\" dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }} />;\n}\n`,
      },
      {
        path: 'src/components/layout/header.tsx',
        content: `import Link from 'next/link';\nimport { siteContent } from '@/content/site-content';\nimport { Container } from '@/components/ui/container';\n\nexport function Header() {\n  return (\n    <header className=\"sticky top-0 z-40 border-b border-white/10 bg-black/70 backdrop-blur-xl\">\n      <Container className=\"flex min-h-16 items-center justify-between gap-6\">\n        <Link href=\"#top\" className=\"text-sm font-semibold tracking-wide text-white\">{siteContent.navigation.logo}</Link>\n        <nav className=\"hidden items-center gap-5 text-sm text-white/70 md:flex\">\n          {siteContent.navigation.menuItems.slice(0, 5).map((item) => <a key={item} href={\`#\${item.toLowerCase().replace(/\\\\s+/g, '-')}\`} className=\"transition hover:text-white\">{item}</a>)}\n        </nav>\n        <a href=\"#contact\" className=\"rounded-full bg-white px-4 py-2 text-sm font-semibold text-black transition hover:bg-white/85\">{siteContent.navigation.ctaButton ?? siteContent.hero.primaryButton}</a>\n      </Container>\n    </header>\n  );\n}\n`,
      },
      {
        path: 'src/components/layout/footer.tsx',
        content: `import { siteContent } from '@/content/site-content';\nimport { Container } from '@/components/ui/container';\n\nexport function Footer() {\n  return (\n    <footer id=\"contact\" className=\"border-t border-white/10 bg-black py-10 text-white/70\">\n      <Container className=\"flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between\">\n        <p className=\"font-semibold text-white\">{siteContent.productName}</p>\n        <p className=\"max-w-xl text-sm\">{siteContent.productDescription}</p>\n      </Container>\n    </footer>\n  );\n}\n`,
      },
      {
        path: 'src/components/landing/hero-section.tsx',
        content: `import { siteContent } from '@/content/site-content';\nimport { Container } from '@/components/ui/container';\n\nexport function HeroSection() {\n  return (\n    <section id=\"top\" className=\"relative overflow-hidden bg-[radial-gradient(circle_at_20%_10%,var(--color-accent),transparent_28%),linear-gradient(135deg,#080808,#1b1b1b_55%,#121212)] py-24 text-white sm:py-32\">\n      <Container className=\"grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center\">\n        <div>\n          {siteContent.hero.badge ? <p className=\"mb-6 inline-flex rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm text-white/80\">{siteContent.hero.badge}</p> : null}\n          <h1 className=\"max-w-4xl text-5xl font-black leading-none sm:text-6xl lg:text-7xl\">{siteContent.hero.headline}</h1>\n          <p className=\"mt-6 max-w-2xl text-lg leading-8 text-white/72\">{siteContent.hero.description}</p>\n          <div className=\"mt-9 flex flex-wrap gap-3\">\n            <a href=\"#contact\" className=\"rounded-full bg-white px-6 py-3 text-sm font-bold text-black transition hover:bg-white/85\">{siteContent.hero.primaryButton}</a>\n            <a href=\"#sections\" className=\"rounded-full border border-white/20 px-6 py-3 text-sm font-bold text-white transition hover:bg-white/10\">{siteContent.hero.secondaryButton}</a>\n          </div>\n        </div>\n        <div className=\"rounded-[2rem] border border-white/12 bg-white/10 p-5 shadow-2xl backdrop-blur\">\n          <div className=\"grid gap-4\">\n            {siteContent.metrics.map((metric) => <div key={metric.label} className=\"rounded-3xl bg-black/35 p-6\"><p className=\"text-4xl font-black\">{metric.value}</p><p className=\"mt-2 text-sm text-white/65\">{metric.label}</p></div>)}\n          </div>\n        </div>\n      </Container>\n    </section>\n  );\n}\n`,
      },
      {
        path: 'src/components/landing/sections-grid.tsx',
        content: `import { siteContent } from '@/content/site-content';\nimport { Container } from '@/components/ui/container';\n\nexport function SectionsGrid() {\n  return (\n    <section id=\"sections\" className=\"bg-[var(--color-background)] py-20\">\n      <Container>\n        <div className=\"grid gap-5 md:grid-cols-2 lg:grid-cols-3\">\n          {siteContent.sections.map((section, index) => (\n            <article key={section.id} id={section.title.toLowerCase().replace(/\\s+/g, '-')} className=\"rounded-3xl border border-[var(--color-border)] bg-[var(--color-surface)] p-7 shadow-sm\">\n              <p className=\"text-sm font-bold text-[var(--color-accent)]\">{String(index + 1).padStart(2, '0')} / {section.type}</p>\n              <h2 className=\"mt-4 text-2xl font-black text-[var(--color-text-primary)]\">{section.title}</h2>\n              <p className=\"mt-3 text-base leading-7 text-[var(--color-text-secondary)]\">{section.goal}</p>\n              <ul className=\"mt-6 space-y-3 text-sm text-[var(--color-text-secondary)]\">\n                {section.requiredElements.slice(0, 4).map((item) => <li key={item} className=\"rounded-2xl bg-black/5 px-4 py-3\">{item}</li>)}\n              </ul>\n            </article>\n          ))}\n        </div>\n      </Container>\n    </section>\n  );\n}\n`,
      },
      {
        path: 'src/components/landing/cta-section.tsx',
        content: `import { siteContent } from '@/content/site-content';\nimport { Container } from '@/components/ui/container';\n\nexport function CtaSection() {\n  return (\n    <section className=\"bg-[var(--color-surface)] py-20\">\n      <Container>\n        <div className=\"rounded-[2rem] bg-black p-8 text-white sm:p-12 lg:p-16\">\n          <h2 className=\"max-w-3xl text-4xl font-black leading-tight sm:text-5xl\">{siteContent.cta.title}</h2>\n          <p className=\"mt-5 max-w-2xl text-lg leading-8 text-white/70\">{siteContent.cta.description}</p>\n          <a href=\"#contact\" className=\"mt-8 inline-flex rounded-full bg-white px-6 py-3 text-sm font-bold text-black transition hover:bg-white/85\">{siteContent.cta.button}</a>\n        </div>\n      </Container>\n    </section>\n  );\n}\n`,
      },
      {
        path: 'src/components/landing/landing-page.tsx',
        content: `import { Header } from '@/components/layout/header';\nimport { Footer } from '@/components/layout/footer';\nimport { StructuredData } from '@/components/seo/structured-data';\nimport { HeroSection } from './hero-section';\nimport { SectionsGrid } from './sections-grid';\nimport { CtaSection } from './cta-section';\n\nexport function LandingPage() {\n  return (\n    <>\n      <StructuredData />\n      <Header />\n      <main>\n        <HeroSection />\n        <SectionsGrid />\n        <CtaSection />\n      </main>\n      <Footer />\n    </>\n  );\n}\n`,
      },
    ];
  }

  private createFallbackCssVariables(designTokens: DesignTokens): string {
    const colors = designTokens.colors;
    return [
      `  --color-background: ${colors.background || '#f7f4ef'};`,
      `  --color-text-primary: ${colors.textPrimary || '#101010'};`,
      `  --color-text-secondary: ${colors.textSecondary || '#4b5563'};`,
      `  --color-accent: ${colors.accent || '#ef4444'};`,
      `  --color-surface: ${colors.surface || '#ffffff'};`,
      `  --color-border: ${colors.border || '#e5e7eb'};`,
    ].join('\n');
  }

  private normalizeGeneratedFiles(files: GeneratedFile[]): GeneratedFile[] {
    const allowedExtensions = new Set(['.ts', '.tsx', '.css']);

    const normalizedFiles = files
      .filter((file) => {
        const normalizedPath = file.path.replaceAll('\\', '/');
        const extension = path.extname(normalizedPath);

        return (
          normalizedPath &&
          !path.isAbsolute(normalizedPath) &&
          !normalizedPath.split('/').includes('..') &&
          allowedExtensions.has(extension)
        );
      })
      .map((file) => ({
        path: this.canonicalizeGeneratedPath(file.path.replaceAll('\\', '/')),
        content: file.content,
      }));

    const requiredPaths = [
      'src/app/page.tsx',
      'src/app/layout.tsx',
      'src/app/globals.css',
      'src/components/landing/landing-page.tsx',
    ];
    const paths = new Set(normalizedFiles.map((file) => file.path));
    const missingPaths = requiredPaths.filter(
      (requiredPath) => !paths.has(requiredPath),
    );

    if (missingPaths.length > 0) {
      this.logger.warn(
        `AI returned files: ${normalizedFiles.map((file) => file.path).join(', ')}`,
      );
      throw new Error(
        `AI did not return required Next.js files: ${missingPaths.join(', ')}`,
      );
    }

    this.validateGeneratedFileReferences(normalizedFiles);

    return normalizedFiles;
  }

  private canonicalizeGeneratedPath(filePath: string): string {
    const normalized = filePath.replace(/^\.\/+/, '');
    const lower = normalized.toLowerCase();

    const aliases: Record<string, string> = {
      'src/components/landing/landingpage.tsx':
        'src/components/landing/landing-page.tsx',
      'src/components/landing/landing-page/index.tsx':
        'src/components/landing/landing-page.tsx',
      'src/components/landing/index.tsx':
        'src/components/landing/landing-page.tsx',
      'src/components/landing/page.tsx':
        'src/components/landing/landing-page.tsx',
      'components/landing/landing-page.tsx':
        'src/components/landing/landing-page.tsx',
      'components/landing/landingpage.tsx':
        'src/components/landing/landing-page.tsx',
    };

    return aliases[lower] ?? normalized;
  }

  private validateGeneratedFileReferences(files: GeneratedFile[]): void {
    const paths = new Set(files.map((file) => file.path));
    const importPattern =
      /(?:import|export)\s+(?:type\s+)?(?:[\s\S]*?\s+from\s+)?['"]([^'"]+)['"]|import\(\s*['"]([^'"]+)['"]\s*\)/g;

    for (const file of files) {
      if (!['.ts', '.tsx'].includes(path.posix.extname(file.path))) {
        continue;
      }

      const currentDir = path.posix.dirname(file.path);
      const missingImports = new Set<string>();
      let match: RegExpExecArray | null;

      while ((match = importPattern.exec(file.content)) !== null) {
        const specifier = match[1] ?? match[2];
        const resolvedPath = this.resolveGeneratedImportPath(
          specifier,
          currentDir,
        );

        if (!resolvedPath) {
          continue;
        }

        if (!this.hasGeneratedImportTarget(paths, resolvedPath)) {
          missingImports.add(specifier);
        }
      }

      if (missingImports.size > 0) {
        throw new Error(
          `AI returned ${file.path} with missing local imports: ${[
            ...missingImports,
          ].join(', ')}`,
        );
      }
    }
  }

  private resolveGeneratedImportPath(
    specifier: string,
    currentDir: string,
  ): string | null {
    if (specifier.startsWith('@/')) {
      return path.posix.normalize(`src/${specifier.slice(2)}`);
    }

    if (specifier.startsWith('./') || specifier.startsWith('../')) {
      const resolvedPath = path.posix.normalize(
        path.posix.join(currentDir, specifier),
      );

      return resolvedPath.startsWith('src/') ? resolvedPath : null;
    }

    return null;
  }

  private hasGeneratedImportTarget(paths: Set<string>, importPath: string) {
    if (paths.has(importPath)) {
      return true;
    }

    const candidates = [
      `${importPath}.ts`,
      `${importPath}.tsx`,
      `${importPath}.css`,
      path.posix.join(importPath, 'index.ts'),
      path.posix.join(importPath, 'index.tsx'),
    ];

    return candidates.some((candidate) => paths.has(candidate));
  }
}
