import { Injectable, Logger } from '@nestjs/common';
import { promises as fs } from 'node:fs';
import path from 'node:path';

import type { DesignTokens, ProjectSpec } from '../ai/ai.types';
import { AiService } from '../ai/ai.service';

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface ProjectManifest {
  projectType: string;
  title: string;
  entrypoint: string;
  files: string[];
  commands: {
    install: string;
    dev: string;
    build: string;
  };
}

@Injectable()
export class CodeGeneratorService {
  private readonly logger = new Logger(CodeGeneratorService.name);

  constructor(private readonly aiService: AiService) {}

  /**
   * Generate all project files — scaffolding is templated, UI code comes from AI
   */
  async generateProjectFiles(
    brief: string,
    projectSpec: ProjectSpec,
    designTokens: DesignTokens,
    designDescription: string,
    codePath: string,
  ): Promise<GeneratedFile[]> {
    this.logger.log('Generating project files (scaffolding + AI code)');

    const aiCode = await this.aiService.generateCode(
      brief,
      projectSpec,
      designTokens,
      designDescription,
    );

    const files: GeneratedFile[] = [
      {
        path: 'package.json',
        content: this.createPackageJson(projectSpec),
      },
      {
        path: 'next.config.mjs',
        content: this.createNextConfig(),
      },
      {
        path: 'tsconfig.json',
        content: this.createTsConfig(),
      },
      {
        path: 'tailwind.config.ts',
        content: this.createTailwindConfig(),
      },
      {
        path: 'postcss.config.mjs',
        content: this.createPostCssConfig(),
      },
      {
        path: 'next-env.d.ts',
        content:
          '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// This file is generated by Next.js.\n',
      },
      ...this.normalizeGeneratedFiles(aiCode.files),
      {
        path: 'README.md',
        content: this.createReadme(projectSpec),
      },
    ];

    await this.writeFiles(files, codePath);

    return files;
  }

  /**
   * Generate project manifest
   */
  generateManifest(
    projectSpec: ProjectSpec,
    files: GeneratedFile[],
  ): ProjectManifest {
    return {
      projectType: 'next-tailwind',
      title: projectSpec.copy.headline,
      entrypoint: 'app/page.tsx',
      files: files.map((file) => file.path),
      commands: {
        install: 'npm install',
        dev: 'npm run dev',
        build: 'npm run build',
      },
    };
  }

  /**
   * Generate reference SVG via AI
   */
  async generateReferenceSvg(
    brief: string,
    projectSpec: ProjectSpec,
    designTokens: DesignTokens,
    designDescription: string,
  ): Promise<string> {
    return this.aiService.generateReferenceSvg(
      brief,
      projectSpec,
      designTokens,
      designDescription,
    );
  }

  private async writeFiles(
    files: GeneratedFile[],
    basePath: string,
  ): Promise<void> {
    await Promise.all(
      files.map(async (file) => {
        const filePath = path.join(basePath, file.path);
        const dir = path.dirname(filePath);
        await fs.mkdir(dir, { recursive: true });
        await fs.writeFile(filePath, file.content, 'utf8');
      }),
    );
  }

  private createPackageJson(projectSpec: ProjectSpec): string {
    const packageName = projectSpec.copy.headline
      .toLowerCase()
      .replace(/[^a-zа-я0-9]+/gi, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 48);

    return `${JSON.stringify(
      {
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
        },
        dependencies: {
          next: '^15.1.0',
          react: '^19.0.0',
          'react-dom': '^19.0.0',
        },
        devDependencies: {
          '@types/react': '^19.0.0',
          '@types/react-dom': '^19.0.0',
          autoprefixer: '^10.4.20',
          postcss: '^8.4.49',
          tailwindcss: '^3.4.17',
          typescript: '^5.7.0',
        },
        private: true,
        name: packageName || 'generated-landing',
        version: '0.0.0',
        type: 'module',
      },
      null,
      2,
    )}\n`;
  }

  private createNextConfig(): string {
    return `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
`;
  }

  private createTsConfig(): string {
    return `${JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2017',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: false,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          plugins: [{ name: 'next' }],
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules'],
      },
      null,
      2,
    )}\n`;
  }

  private createTailwindConfig(): string {
    return `import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;
`;
  }

  private createPostCssConfig(): string {
    return `const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

export default config;
`;
  }

  private createReadme(projectSpec: ProjectSpec): string {
    return `# ${projectSpec.copy.headline}

Generated Next.js + Tailwind site.

## Commands

\`\`\`bash
npm install
npm run dev
npm run build
\`\`\`
`;
  }

  private normalizeGeneratedFiles(files: GeneratedFile[]): GeneratedFile[] {
    const allowedExtensions = new Set(['.ts', '.tsx', '.css']);

    const normalizedFiles = files
      .filter((file) => {
        const normalizedPath = file.path.replaceAll('\\', '/');
        const extension = path.extname(normalizedPath);

        return (
          normalizedPath &&
          !path.isAbsolute(normalizedPath) &&
          !normalizedPath.split('/').includes('..') &&
          allowedExtensions.has(extension)
        );
      })
      .map((file) => ({
        path: file.path.replaceAll('\\', '/'),
        content: file.content,
      }));

    const requiredPaths = ['app/page.tsx', 'app/layout.tsx', 'app/globals.css'];
    const paths = new Set(normalizedFiles.map((file) => file.path));
    const missingPaths = requiredPaths.filter(
      (requiredPath) => !paths.has(requiredPath),
    );

    if (missingPaths.length > 0) {
      throw new Error(
        `AI did not return required Next.js files: ${missingPaths.join(', ')}`,
      );
    }

    return normalizedFiles;
  }
}
