export enum ArtifactType {
  ReferenceImage = 'reference_image',
  ReferenceContextSummary = 'reference_context_summary',
  ProjectSpec = 'project_spec',
  ProjectSpecSummary = 'project_spec_summary',
  DesignDescription = 'design_description',
  DesignTokens = 'design_tokens',
  DesignContextSummary = 'design_context_summary',
  FrontendProject = 'frontend_project',
  DesktopScreenshot = 'desktop_screenshot',
  MobileScreenshot = 'mobile_screenshot',
  VisualReport = 'visual_report',
  DiffImage = 'diff_image',
  BuildError = 'build_error',
  BuildLog = 'build_log',
  ReferenceValidation = 'reference_validation',
}
