export enum ArtifactType {
  ReferenceImage = 'reference_image',
  ReferenceBlock = 'reference_block',
  ReferenceContextSummary = 'reference_context_summary',
  StyleVariants = 'style_variants',
  StyleVariantImage = 'style_variant_image',
  SelectedStyle = 'selected_style',
  CodePlan = 'code_plan',
  CodeContentModule = 'code_content_module',
  CodeLayoutModule = 'code_layout_module',
  CodeSectionsModule = 'code_sections_module',
  FrontendProject = 'frontend_project',
  DesktopScreenshot = 'desktop_screenshot',
  MobileScreenshot = 'mobile_screenshot',
  VisualReport = 'visual_report',
  DiffImage = 'diff_image',
  BuildError = 'build_error',
  BuildLog = 'build_log',
  ReferenceValidation = 'reference_validation',
}
